const recipes = [
  {
    id: 1,
    label: "Chicken Pasta",
    category: "Dinner",
    // image: image1,
    description: "A delicious chicken pasta dish with tomato sauce.",
    ingredients: ["Chicken", "Pasta", "Tomato Sauce"],
    price: 12.99,
  },
  {
    id: 2,
    label: "Vegetarian Salad",
    category: "Lunch",
    image: "../../assets/image2.jpg",
    description:
      "A refreshing salad with lettuce, tomato, cucumber, and dressing.",
    ingredients: ["Lettuce", "Tomato", "Cucumber", "Dressing"],
    price: 8.99,
  },
  {
    id: 3,
    label: "Spaghetti Bolognese",
    category: "Dinner",
    image: "../../assets/image3.jpg",

    description: "Classic spaghetti with a hearty meat sauce.",
    ingredients: ["Spaghetti", "Ground Beef", "Tomato Sauce"],
    price: 10.99,
  },
  {
    id: 4,
    label: "Avocado Toast",
    category: "Breakfast",
    image: "../../assets/image4.jpg",

    description: "A simple and healthy breakfast with avocado on toast.",
    ingredients: ["Avocado", "Bread", "Salt", "Pepper"],
    price: 6.99,
  },
  {
    id: 5,
    label: "Grilled Chicken Wrap",
    category: "Lunch",
    image: "../../assets/image5.jpg",

    description:
      "Grilled chicken wrapped in a tortilla with veggies and sauce.",
    ingredients: ["Grilled Chicken", "Tortilla", "Vegetables", "Sauce"],
    price: 9.99,
  },
  {
    id: 6,
    label: "Eggs Benedict",
    image: "../../assets/image6.jpg",
    category: "Breakfast",
    description: "Poached eggs on English muffins with hollandaise sauce.",
    ingredients: ["Eggs", "English Muffins", "Hollandaise Sauce"],
    price: 11.99,
  },
  {
    id: 7,
    label: "Caesar Salad",
    image: "../../assets/image7.jpg",
    category: "Lunch",
    description: "Classic Caesar salad with croutons and parmesan cheese.",
    ingredients: ["Romaine Lettuce", "Croutons", "Parmesan", "Caesar Dressing"],
    price: 7.99,
  },
  {
    id: 8,
    label: "Shrimp Scampi",
    image: "../../assets/image8.jpg",
    category: "Dinner",
    description: "Garlic butter shrimp served over pasta.",
    ingredients: ["Shrimp", "Butter", "Garlic", "Pasta"],
    price: 14.99,
  },
  {
    id: 9,
    label: "Pancakes with Maple Syrup",
    image: "../../assets/image9.jpg",
    category: "Breakfast",
    description: "Fluffy pancakes drizzled with maple syrup.",
    ingredients: ["Pancakes", "Maple Syrup"],
    price: 8.49,
  },
  {
    id: 10,
    label: "Caprese Salad",
    image: "../../assets/image10.jpg",
    category: "Lunch",
    description:
      "Fresh tomato, mozzarella, and basil salad with balsamic glaze.",
    ingredients: ["Tomato", "Mozzarella", "Basil", "Balsamic Glaze"],
    price: 10.99,
  },
  {
    id: 11,
    label: "Beef Stir-Fry",
    image: "../../assets/image11.jpg",
    category: "Dinner",
    description: "Tender beef strips stir-fried with colorful vegetables.",
    ingredients: ["Beef Strips", "Vegetables", "Soy Sauce"],
    price: 13.99,
  },
  {
    id: 12,
    label: "Fruit Parfait",
    image: "../../assets/image12.jpg",
    category: "Breakfast",
    description: "Layers of yogurt, granola, and fresh fruit.",
    ingredients: ["Yogurt", "Granola", "Berries", "Honey"],
    price: 9.99,
  },
];

export default recipes;
